#!/bin/sh
#SBATCH -J ED_SERVER
#SBATCH -o ED_SERVER.%J.stdout
#SBATCH -e ED_SERVER.%J.stderr
#SBATCH -N 8
#SBATCH -p short
#SBATCH --qos short-award
#SBATCH -t 00:02:00
#SBATCH --ntasks-per-node=16

module unload openmpi/1.10.1
module load mpich

source /home1/zw241/.grpc

rm -rf multinodeip


module load python/3.6.3
cd ~/pythonWorkSpace/nbodysimulation/
source ./bin/activate

PRJPATH=/project1/parashar-001/zw241/software/eventDrivenWorkflow/tests/performance
cd $PRJPATH

NUM_SERVER=1
NUM_CLIENT=128
NUM_CLIENT_TASK=256
NUM_GROUPSIZE=1
NUM_GROUP=1
THREAD_POOL=512
NOTIFY_SLEEP=1000
COORDINATOR_THRESHOLD=1024
DIR=.

mpirun --map-by ppr:16:node -n $NUM_SERVER  ./workflowserver 1500 eno1 $NUM_GROUPSIZE $NUM_GROUP $THREAD_POOL $NOTIFY_SLEEP $COORDINATOR_THRESHOLD >& $DIR/server_"$NUM_SERVER"_"$NUM_CLIENT"_"$NUM_CLIENT_TASK".log  &

# check if start ok
/bin/bash serverStartOk.sh 1


mpirun --map-by ppr:16:node -n $NUM_CLIENT ./eventNotify $NUM_CLIENT_TASK 10 eno1 $NUM_GROUP $NUM_GROUPSIZE >& $DIR/client_"$NUM_SERVER"_"$NUM_CLIENT"_"$NUM_CLIENT_TASK".log  &

wait