#!/bin/sh
#SBATCH -J ED_SERVER
#SBATCH -o ED_SERVER.%J.stdout
#SBATCH -e ED_SERVER.%J.stderr
#SBATCH -N 3
#SBATCH -p short
#SBATCH --qos short-award
#SBATCH -t 00:05:00
#SBATCH --ntasks-per-node=18

module unload openmpi/1.10.1
module load mpich
module load python/3.6.3

cd ~/pythonWorkSpace/nbodysimulation/
source ./bin/activate

PRJPATH=/project1/parashar-001/zw241/software/eventDrivenWorkflow/tests/performance

# start DataSpaces

module unload openmpi/1.10.1
module load mpich
module load python/3.6.3
cd ~/pythonWorkSpace/nbodysimulation/
source ./bin/activate
cd /home1/zw241/dataspaces/tests/C
./dataspaces_server -c 2 -s 1 >& $PRJPATH/wftest_dsserver.log  &


# start Workflow Server (pub/sub broker)

source /home1/zw241/.grpc
cd $PRJPATH
rm -rf multinodeip

NUM_SERVER=1
NUM_CLIENT=100
NUM_CLIENT_TASK=256
NUM_GROUPSIZE=1
NUM_GROUP=1
THREAD_POOL=64
NOTIFY_SLEEP=10000
COORDINATOR_THRESHOLD=1024

mpirun --map-by ppr:16:node -n $NUM_SERVER  ./workflowserver 1500 eno1 $NUM_GROUPSIZE $NUM_GROUP $THREAD_POOL $NOTIFY_SLEEP $COORDINATOR_THRESHOLD >& $PRJPATH/wftest_wfserver.log  &

# check if start ok
/bin/bash serverStartOk.sh 1

# start the operator

#module load mpich
#module load python/3.6.3
#cd /home1/zw241/pythonWorkSpace/nbodysimulation
#source ./bin/activate
#cd $PRJPATH
#source /home1/zw241/.grpc
#./operator >& $PRJPATH/wftest_operator.log  &

# start the simulation

#module load mpich
#module load python/3.6.3
#cd /home1/zw241/pythonWorkSpace/nbodysimulation
#source ./bin/activate

#cd /project1/parashar-001/zw241/software/eventDrivenWorkflow/tests/movingGridInStaging

#python semiEulerGridInStaging.py >& $PRJPATH/wftest_simulation.log  &

wait