#!/bin/sh
#SBATCH -J ED_SERVER
#SBATCH -o ED_SERVER.%J.stdout
#SBATCH -e ED_SERVER.%J.stderr
#SBATCH -N 1
#SBATCH -p short
#SBATCH --qos short-award
#SBATCH -t 00:02:00
#SBATCH --ntasks-per-node=16

module unload openmpi/1.10.1
module load mpich

source /home1/zw241/.grpc

rm -rf multinodeip


PRJPATH=/project1/parashar-001/zw241/software/eventDrivenWorkflow/tests/performance

cd $PRJPATH

NUM_SERVER=20
NUM_CLIENT=1
NUM_CLIENT_TASK=10240
NUM_GROUPSIZE=1
NUM_GROUP=4
THREAD_POOL=128
NOTIFY_SLEEP=500000
COORDINATOR_THRESHOLD=1024
DIR=.

mpirun --map-by ppr:16:node -n $NUM_SERVER  ./workflowserver 1500 eno1 $NUM_GROUPSIZE $NUM_GROUP $THREAD_POOL $NOTIFY_SLEEP $COORDINATOR_THRESHOLD >& $DIR/server_"$NUM_SERVER"_"$NUM_CLIENT"_"$NUM_CLIENT_TASK".log  &

# check if start ok
/bin/bash serverStartOk.sh 20


mpirun --map-by ppr:16:node -n $NUM_CLIENT ./eventNotify $NUM_CLIENT_TASK 10 eno1 $NUM_GROUP $NUM_GROUPSIZE >& $DIR/client_"$NUM_SERVER"_"$NUM_CLIENT"_"$NUM_CLIENT_TASK".log  &

wait