#!/bin/sh
#SBATCH -J ED_SERVER
#SBATCH -o ED_SERVER.%J.stdout
#SBATCH -e ED_SERVER.%J.stderr
#SBATCH -N 1
#SBATCH -p short
#SBATCH --qos short-award
#SBATCH -t 00:02:00
#SBATCH --ntasks-per-node=16

module unload openmpi/1.10.1
module load mpich

source /home1/zw241/.grpc

rm -rf multinodeip


PRJPATH=/project1/parashar-001/zw241/software/eventDrivenWorkflow/tests/performance

cd $PRJPATH

NUM_SERVER=1
NUM_CLIENT=1
NUM_CLIENT_TASK=12
NUM_GROUPSIZE=1
NUM_GROUP=1
DIR=.

mpirun --map-by ppr:16:node -n $NUM_SERVER  ./workflowserver 1500 eno1 $NUM_GROUPSIZE >& $DIR/server_"$NUM_SERVER".log  &

# check if start ok
/bin/bash serverStartOk.sh 1


mpirun --map-by ppr:16:node -n $NUM_CLIENT ./eventNotify $NUM_CLIENT_TASK 10 eno1 $NUM_GROUP >& $DIR/client_"$NUM_SERVER".log  &

wait