#!/bin/sh
#SBATCH -J ED_SERVER
#SBATCH -o ED_SERVER.%J.stdout
#SBATCH -e ED_SERVER.%J.stderr
#SBATCH -N 1
#SBATCH -p short
#SBATCH --qos short-award
#SBATCH -t 00:01:00


module unload openmpi/1.10.1
module load mpich
source /home1/zw241/.grpc


module load python/3.6.3
cd ~/pythonWorkSpace/nbodysimulation/
source ./bin/activate


cd /project1/parashar-001/zw241/software/eventDrivenWorkflow/tests/movingGridMultiDisk

rm -rf image_rank*

mpirun -n 2 python ./semiEulerGridInStaging.py