// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: workflowserver.proto

#include "workflowserver.pb.h"
#include "workflowserver.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace workflowserver {

static const char* Greeter_method_names[] = {
  "/workflowserver.Greeter/SayHello",
  "/workflowserver.Greeter/Subscribe",
  "/workflowserver.Greeter/Publish",
};

std::unique_ptr< Greeter::Stub> Greeter::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Greeter::Stub> stub(new Greeter::Stub(channel));
  return stub;
}

Greeter::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_SayHello_(Greeter_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Subscribe_(Greeter_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Publish_(Greeter_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Greeter::Stub::SayHello(::grpc::ClientContext* context, const ::workflowserver::HelloRequest& request, ::workflowserver::HelloReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SayHello_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::workflowserver::HelloReply>* Greeter::Stub::AsyncSayHelloRaw(::grpc::ClientContext* context, const ::workflowserver::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::workflowserver::HelloReply>::Create(channel_.get(), cq, rpcmethod_SayHello_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::workflowserver::HelloReply>* Greeter::Stub::PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::workflowserver::HelloRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::workflowserver::HelloReply>::Create(channel_.get(), cq, rpcmethod_SayHello_, context, request, false);
}

::grpc::Status Greeter::Stub::Subscribe(::grpc::ClientContext* context, const ::workflowserver::PubSubRequest& request, ::workflowserver::PubSubReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Subscribe_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::workflowserver::PubSubReply>* Greeter::Stub::AsyncSubscribeRaw(::grpc::ClientContext* context, const ::workflowserver::PubSubRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::workflowserver::PubSubReply>::Create(channel_.get(), cq, rpcmethod_Subscribe_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::workflowserver::PubSubReply>* Greeter::Stub::PrepareAsyncSubscribeRaw(::grpc::ClientContext* context, const ::workflowserver::PubSubRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::workflowserver::PubSubReply>::Create(channel_.get(), cq, rpcmethod_Subscribe_, context, request, false);
}

::grpc::Status Greeter::Stub::Publish(::grpc::ClientContext* context, const ::workflowserver::PubSubRequest& request, ::workflowserver::PubSubReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Publish_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::workflowserver::PubSubReply>* Greeter::Stub::AsyncPublishRaw(::grpc::ClientContext* context, const ::workflowserver::PubSubRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::workflowserver::PubSubReply>::Create(channel_.get(), cq, rpcmethod_Publish_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::workflowserver::PubSubReply>* Greeter::Stub::PrepareAsyncPublishRaw(::grpc::ClientContext* context, const ::workflowserver::PubSubRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::workflowserver::PubSubReply>::Create(channel_.get(), cq, rpcmethod_Publish_, context, request, false);
}

Greeter::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::workflowserver::HelloRequest, ::workflowserver::HelloReply>(
          std::mem_fn(&Greeter::Service::SayHello), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::workflowserver::PubSubRequest, ::workflowserver::PubSubReply>(
          std::mem_fn(&Greeter::Service::Subscribe), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::workflowserver::PubSubRequest, ::workflowserver::PubSubReply>(
          std::mem_fn(&Greeter::Service::Publish), this)));
}

Greeter::Service::~Service() {
}

::grpc::Status Greeter::Service::SayHello(::grpc::ServerContext* context, const ::workflowserver::HelloRequest* request, ::workflowserver::HelloReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Greeter::Service::Subscribe(::grpc::ServerContext* context, const ::workflowserver::PubSubRequest* request, ::workflowserver::PubSubReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Greeter::Service::Publish(::grpc::ServerContext* context, const ::workflowserver::PubSubRequest* request, ::workflowserver::PubSubReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace workflowserver

